server {
    listen 80;
    server_name localhost;

    # Указываем корень прямо на папку с твоими файлами
    root /usr/share/nginx/html/ledger-mobile;

    location / {
        index auth.html;
        try_files $uri $uri/ /auth.html;
    }

    location /user/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}